Bcv 3(quote provider)
dsx-tech/student-project-balances-backend pull request #12
Opened 2020-03-03 17:49 UTC by yel1ow

2020-03-06 08:10 UTC, phil-dolgolev requested changes
Тут только прям оч важные штуки дофиксим, и влить это хочется как можно скорее, и уже относительно этого двигаться дальше небольшими задачками.

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/controllers/QuotesProviderController.java
> +    private final String supportedCurrencies = "Supported currencies:\n" +
Чот как-то слишком захардкожено :) Можем потом пофиксить если долго.

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/controllers/QuotesProviderController.java
> +        log.info(
FYI: выглядит так, как будто ты хочешь посыпать тут немного аспектами, и на каждый вызов логировать одно и то же у каждого метода в этом контроллере. Можно сделать более элегантно точно, но потом.

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/converters/DsxInstrumentEdgeToInstrumentConverter.java
> +public class DsxInstrumentEdgeToInstrumentConverter implements Converter<DsxInstrumentEdge, Instrument> {
Интересно откуда такой нейминг пошел, но пока забиваем.

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/ActualDataLoaderService.java
> +        loadDataFromLastBars();
А это получается у нас загрузка разовая на старте только?

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +public class HistoricalDataLoaderService {
Пока не работает или вообще выпиливать будешь?

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +        new Thread(this::loadData).start();
Очень редко ты хочешь напрямую работать с потоками, 99% проблем решают готовые пулы из Executors.

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +    private void sleep() {
Полагаю ты наткнулся на лимиты, и таким образом решил тротлить запросы. Распространенная проблема, могу предложить более элегантное решение - https://github.com/resilience4j/resilience4j (вообще клевые тут штуки для работы со внешними сервисами). Но судя по всему и в спринге из коробки есть красивые решения: https://medium.com/teamarimac/implementing-throttling-in-java-spring-boot-ec4723cfce9f

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/QuoteProviderService.java
> +        var baseCurrencyBars = barService.findByBaseCurrencyAndTimestampBetween(
Надо будет еще разок устно проговорить схему хранения и конвертации, пока есть подозрения что что-то тут бизнесово не то :) Фиксить будем не в этом PR-е

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/quote_providers/alpha_vantage/AlphaVantageApiChecker.java
> +        final var apiKey1 = "PPKFFSGZ5IH9KBU9";
Хе-хе 🙃

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/quote_providers/alpha_vantage/AlphaVantageQuoteProvider.java
> +            "R8E6U7RI11YSJ9YU",
Ключи наверное не в коде и не в гите должны быть в итоге.

2020-03-06 08:10 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/quote_providers/dsx/DsxQuoteProvider.java
> +                throw new RuntimeException(e);
Есть подозрение, что лучше уже в самом RequestService ловить исключения и конвертировать их в Runtime (но лучше завести свой рантайм под наш проект, удобно будет отличать наши исключения от всяких библиотечных)

2020-03-06 08:10 UTC, phil-dolgolev commented on server/src/main/java/dsx/bcv/server/services/TradeService.java
> +        trade.setInstrument(instrumentService.saveIfNotExists(trade.getInstrument()));
Я вроде тут уже объяснял проблемы с этим кодом. Не очень пока понятно как оно тут пофикшено и пофикшено ли.

2020-03-06 16:20 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/controllers/QuotesProviderController.java
> +    private final String supportedCurrencies = "Supported currencies:\n" +
А, это кстати уже не актуально. Исправлю.

2020-03-06 16:21 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/controllers/QuotesProviderController.java
> +        log.info(
Понял

2020-03-06 16:22 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/converters/DsxInstrumentEdgeToInstrumentConverter.java
> +public class DsxInstrumentEdgeToInstrumentConverter implements Converter<DsxInstrumentEdge, Instrument> {
Самому интересно, до сих пор не знаю как назвать))

2020-03-06 16:26 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/ActualDataLoaderService.java
> +        loadDataFromLastBars();
Да, это нужно поменять. Думаю, можно пока запускать это раз в день, т.к. забираются данные из базы, в которой они хранятся с интервалом в день.

2020-03-06 16:32 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +public class HistoricalDataLoaderService {
Работает. Загружает историю при запуске, если база пуста. Можно раскоментить и оставить так. Не вижу смысла упарываться в безотказную работу при любом состоянии бд во время запуска, т.к. если что, её можно перезаписать с нуля за час-два и этот код прекрасно справляется с этим.

2020-03-06 16:33 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +        new Thread(this::loadData).start();
Да, думал об этом, но пока не разобрался. Поменяю позже. К тому же задача довольно массивная)

2020-03-06 16:36 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +    private void sleep() {
Согласен, ткнул простой sleep в надежде найти потом красивое решение. Подумал и так сойдет, потому что этот код, возможно, больше не нужен.

2020-03-06 16:38 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/QuoteProviderService.java
> +        var baseCurrencyBars = barService.findByBaseCurrencyAndTimestampBetween(
Схему нарисую.

2020-03-06 16:38 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/quote_providers/dsx/DsxQuoteProvider.java
> +                throw new RuntimeException(e);
Сделаю.

2020-03-06 16:40 UTC, yel1ow commented on server/src/main/java/dsx/bcv/server/services/TradeService.java
> +        trade.setInstrument(instrumentService.saveIfNotExists(trade.getInstrument()));
Этот код я еще не менял. Не помню, зачем смержил в эту ветку.

2020-03-13 19:34 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/controllers/QuotesProviderController.java
> +    private final String supportedCurrencies = "Supported currencies:\n" +
Исправил.

2020-03-13 19:35 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/ActualDataLoaderService.java
> +        loadDataFromLastBars();
Сделал scheduler раз в день

2020-03-13 19:36 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +    private void sleep() {
Сделал красиво.

2020-03-13 19:42 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/quote_providers/alpha_vantage/AlphaVantageApiChecker.java
> +        final var apiKey1 = "PPKFFSGZ5IH9KBU9";
¯\_(ツ)_/¯

2020-03-13 19:43 UTC, yel1ow commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/quote_providers/dsx/DsxQuoteProvider.java
> +                throw new RuntimeException(e);
Сделал.

2020-03-16 07:27 UTC, phil-dolgolev commented on marketdata-provider/src/main/java/dsx/bcv/marketdata_provider/services/HistoricalDataLoaderService.java
> +public class HistoricalDataLoaderService {
Ну, по хорошему нужно упороться, но пока и правда можно забить

2020-03-16 07:40 UTC, phil-dolgolev requested changes

2020-03-16 07:40 UTC, phil-dolgolev commented on marketdata-provider/src/test/java/dsx/bcv/marketdata_provider/services/quote_providers/dsx/DsxQuoteProviderTest.java
> +        assertTrue(exchangeRate > 60 && exchangeRate < 100);
Довольно интересный assert, а откуда данные берутся и почему не прям конкретное значение? Этот тест что, по сети ходит ?)

2020-03-16 11:35 UTC, yel1ow commented on marketdata-provider/src/test/java/dsx/bcv/marketdata_provider/services/quote_providers/dsx/DsxQuoteProviderTest.java
> +        assertTrue(exchangeRate > 60 && exchangeRate < 100);
У меня были проблемы с формулами и появлялся какой-то такой курс: 0.00001... Точного не знал и сделал так. Этот тест больше не нужен, надо было удалить.

2020-03-21 15:18 UTC, merged